source/OS.EMS.Website/Controllers/LoginController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ninject;
using OS.EMS.Model;
using OS.EMS.Security;
using OS.EMS.Services;
using OS.EMS.Web.Models;

namespace OS.EMS.Web.Controllers
{
    public class LoginController : BaseController
    {
        

        [Inject]
        public LoginController(ISecurityService securityService, ILoginService loginService)
        {
            SecurityService = securityService;
            LoginService = loginService;
        }

        #region CRUD Operations
        [HttpPost]
        public ActionResult SignIn(SignInVM model)
        {
            if (model == null) return RedirectToAction("InvalidRequest", "Error");

            var user = SecurityService.Authenticate(model.EmailAddress, model.Password);
            
            if(user == null)
            {
                ShowMessage(Messages.InvalidEmailPassword, MessageType.Error);
                return RedirectToAction("Index", "Home");
            }

            LoginService.SignIn(user);
            return RedirectToAction("Dashboard", "Home");
        }

        public ActionResult SignOut()
        {
            LoginService.SignOut();
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

source/OS.EMS.Website/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ninject;
using OS.EMS.Model;
using OS.EMS.Services;
using OS.EMS.Model.Helper;
using OS.EMS.Web.Models;

namespace OS.EMS.Web.Controllers
{
    public class StoreController : BaseController
    {
        [Inject]
         public StoreController(IStoreService storeService, IEmployeeService employeeService, IGeographyService geographyService, ISecurityService securityService)
        {
            StoreService = storeService;
            EmployeeService = employeeService;
            GeographyService = geographyService;
            SecurityService = securityService;
        }

        #region CRUD Operations

        public ActionResult Create()
        {
            var viewModel = new StoreVM();
            PopulateGeographySLI(viewModel);

            return View("CreateOrUpdate", viewModel);
        }

        [HttpPost]
        public ActionResult Create(StoreVM viewModel)
        {
            if (viewModel == null) return RedirectToAction("InvalidRequest", "Error");

            var store = viewModel.ToModel();

            if (StoreService.Create(store))
            {
                ShowMessage(Messages.CreateStoreSuccess, MessageType.Success);
                return RedirectToAction("Details", new { id = store.Id });
            }
            return RedirectToAction("InvalidRequest", "Error");
        }

        public ActionResult Update(Guid? id)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            var store = StoreService.Get(id.Value);
            var viewModel = store.ToStoreVM();
            PopulateGeographySLI(viewModel);
            return View("CreateOrUpdate", viewModel);
        }

        [HttpPost]
        public ActionResult Update(StoreVM viewModel)
        {
            if (viewModel == null || viewModel.Id == null) return RedirectToAction("InvalidRequest", "Error");

            var store = viewModel.ToModel();
            if (StoreService.Update(store))
            {
                ShowMessage(Messages.UpdateStoreSuccess, MessageType.Success);
                return RedirectToAction("Details", new{ id=store.Id});
            }

            return RedirectToAction("InvalidRequest", "Error");

        }

        public ActionResult List()
        {
            var user = HttpContext.Session["AppUser"] as SystemUser;
            if (user == null) return RedirectToAction("InvalidRequest", "Error");

            var role = SecurityService.GetRolesById(user.RoleId.Value);

            IEnumerable<Store> stores = null;
            if (user.EmployeeId.HasValue && user.Role.Name == RoleType.Manager.ToString())
            {
                stores = StoreService.GetByManagerId(user.EmployeeId.Value);
            }
            else if (user.Role.Name == RoleType.Admin.ToString())
            {
                stores = StoreService.GetAll();
            }
            else{
                return RedirectToAction("InvalidRequest", "Error");
            }

            
            //var stores = (role.Name == RoleType.Manager.ToString()) ? StoreService.GetByManagerId(user.EmployeeId.Value) : StoreService.GetAll();
            var storesVM = stores.ToStoreVM();
            return View(storesVM);
            
        }

        public ActionResult Activate(Guid? id, bool active)
        {
            if (!id.HasValue) return RedirectToAction("InvalidRequest", "Error");

            if (StoreService.Activate(id.Value, active))
            {
                ShowMessage(active ? Messages.ActivateStoreSuccess : Messages.DeactivateStoreSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult SearchByCode(string StoreCode)
        {
            if (string.IsNullOrEmpty(StoreCode))
            {
                return RedirectToAction("Dashboard", "Home");
            }

            var stores = StoreService.SearchByCode(StoreCode);
            var storesVM = stores.ToStoreVM();

            if (storesVM.Count() == 1)
            {
                var viewModel = storesVM.FirstOrDefault();
                PopulateGeographySLI(viewModel);

                ////For Employees of Store
                //if (viewModel != null && viewModel.Id.HasValue)
                //{
                //    ForStoreEmployees(viewModel.Id.Value);
                //}

                return View("Details", viewModel);
            }
            else if (storesVM.Count() > 1)
            {
                return View("List", storesVM);
            }

            return RedirectToAction("Dashboard", "Home");
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            var store = StoreService.Get(id.Value);
            var viewModel = store.ToStoreVM();

            ////For Employees of Store
            //if (store != null)
            //{
            //    ForStoreEmployees(store.Id);
            //}
            return View(viewModel);
        }

        public ActionResult SetSupervisor(Guid id, Guid eid, Guid? peid)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            if(StoreService.SetSupervisor(id, eid, peid)){
                ShowMessage(Messages.AssignSupervisorStoreSuccess, MessageType.Success);
                return RedirectToAction("Details", new { id = id});
            }

            return RedirectToAction("List");

        }

        [HttpGet]
        public virtual JsonResult IsEmailExists(string Email, string InitialEmail)
        {
            //Thread.Sleep(2000);//fake delay
            if (Email == InitialEmail)
            {
                return this.Json(true, JsonRequestBehavior.AllowGet);
            }

            return this.Json(!StoreService.IsEmailExists(Email), JsonRequestBehavior.AllowGet);

        }

        #endregion

        #region AppHelper

        private void PopulateGeographySLI(StoreVM viewModel)
        {
            var states = GeographyService.GetStates();
            viewModel.States = states.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Name });

            var cities = GeographyService.GetCities();
            viewModel.Cities = cities.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name });
        }

        #endregion

    }
}

source/OS.EMS.Website/Controllers/UserController.cs
using System;
using System.Web.Mvc;
using OS.EMS.Model;
using OS.EMS.Services;
using OS.EMS.Model.Helper;
using OS.EMS.Web.Models;
using Ninject;
using System.Collections.Generic;
using System.Linq;

namespace OS.EMS.Web.Controllers
{
    public class UserController : BaseController
    {

        [Inject]
        public UserController(ISecurityService securityService, IEmployeeService employeeService)
        {
            SecurityService = securityService;
            EmployeeService = employeeService;
        }

        #region CRUD Operations
        public ActionResult Create()
        {
            var viewModel = new SystemUserVM();
            PopulateRoleForSLI(viewModel);
            PopulateSupervisorForSLI(viewModel);
            return View("CreateOrUpdate", viewModel);

        }

        [HttpPost]
        public ActionResult Create(SystemUserVM viewModel)
        {
            if (viewModel == null) return RedirectToAction("InvalidRequest", "Error");

            var user = viewModel.ToModel();

            if (SecurityService.Create(user))
            {
                ShowMessage(Messages.CreateUserSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("InvalidRequest", "Error");

        }

        public ActionResult Update(Guid? id)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            var user = SecurityService.Get(id.Value);
            var viewModel = user.ToSystemUserVM();
            viewModel.PasswordConfirm = viewModel.Password;

            PopulateRoleForSLI(viewModel);
            PopulateSupervisorForSLI(viewModel);

            return View("CreateOrUpdate", viewModel);
        }

        [HttpPost]
        public ActionResult Update(SystemUserVM viewModel)
        {
            if (viewModel == null || viewModel.Id == null) return RedirectToAction("InvalidRequest", "Error");

            //var user = SecurityService.Get(viewModel.Id.Value);
            var model = viewModel.ToModel();
            if (SecurityService.Update(model))
            {
                ShowMessage(Messages.UpdateUserSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("InvalidRequest", "Error");

        }

        public ActionResult List()
        {
            var users = SecurityService.GetAll();
            return View(users);
        }

        public ActionResult Activate(Guid? id, bool active)
        {
            if (!id.HasValue) return RedirectToAction("InvalidRequest", "Error");

            if (SecurityService.Activate(id.Value, active))
            {
                ShowMessage(active ? Messages.ActivateUserSuccess : Messages.DeactivateUserSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }

        public ActionResult AssociateSystemUser(Guid? id)
        {
            if (!id.HasValue) return RedirectToAction("InvalidRequest", "Error");

            Employee employee = EmployeeService.Get(id.Value);

            //For Mapping matcing Values
            var viewModel = new SystemUserVM();
            Utils.Map(employee, viewModel);
            viewModel.Id = null;
            viewModel.EmployeeId = id.Value;

            PopulateRoleForSLI(viewModel);
            //PopulateSupervisorForSLI(viewModel);

            return View("CreateOrUpdate", viewModel);

        }

        [HttpGet]
        public virtual JsonResult IsEmailExists(string Email, string InitialEmail)
        {
            //Thread.Sleep(2000);//fake delay
            if (Email == InitialEmail)
            {
                return this.Json(true, JsonRequestBehavior.AllowGet);
            }
            return this.Json(!SecurityService.IsEmailExists(Email), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region HelperMethods
        private void PopulateRoleForSLI(SystemUserVM viewModel)
        {
            var roles = SecurityService.GetRoles();
            viewModel.Roles = roles.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Name }).OrderByDescending(x => x.Value);
        }

        private void PopulateSupervisorForSLI(SystemUserVM viewModel)
        {
            var managers = EmployeeService.GetManagers(true);
            viewModel.Managers = managers.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = string.Format("{0} {1} [{2}]", s.LastName, s.FirstName, s.Code) });
        }
        #endregion
    }
}

source/OS.EMS.Website/Views/Shared/PageMessage.cshtml
@using OS.EMS.Web.Models


@*For Page Messages*@

@{
    var message = (MessageVM)TempData["Message"];
}

@if (message != null)
{
    <div class="alert alert-@(message.Type)" style="margin-bottom: 6px;">
        @message.Text<a href="#" class="alert-link pull-right">close</a>
        @(TempData["Message"] = null)
    </div>
    
    <script>
        $(function () {
            $(".alert").click(function () {
                $(this).hide();
            });
        });
    </script>
}

source/OS.EMS.Website/Views/Shared/_BreadCrumb.cshtml
@{

    var RequestUrl = Request.AppRelativeCurrentExecutionFilePath;

    if (!string.IsNullOrWhiteSpace(RequestUrl))
    {
        var SplitData = RequestUrl.Split('/');
        if (SplitData.Count() >= 2)
        {
            var lstSplitData = SplitData.ToList();
            lstSplitData.RemoveAt(0);
            
            
    <a href="@Url.Action("Dashboard", "Home")" class="AppAnc" style="float: left;">
        <i class="fa fa-home" style="display: block; float: left; font-size: 20px; margin-right: 8px; margin-top: 6px;"></i>@*<div style="display: block; float: left; margin-top: 8px; margin-right: 8px;">/</div>*@
    </a>
    <ul class="breadcrumb" style="margin-bottom: 0px;">
        @{
            int count = 0;

            foreach (var item in lstSplitData)
            {
                count++;
                var display = item;

                switch (item)
                {
                    //case "Update":
                    //    display = "Edit";
                    //    break;
                    case "Home":
                        display = "";
                        break;
                }
                if (count < 3)
                {
                    if (count == 2)
                    {
            <li class="active">@display</li>
                    }
                    else
                    {
@*<li><a href="#">@display</a></li>*@
            <li>@display</li>
                    }
                }
            }
        }
    </ul>
        }

        var end = "bread";
    }
}

source/OS.EMS.Website/Views/Shared/_EmployeeList.cshtml
@model IEnumerable<OS.EMS.Web.Models.EmployeeVM>

<div class="RC GridHeaderBG">
    <div class="pull-left GridCP" style="width: 15%;">Code</div>
    <div class="pull-left GridCP" style="width: 20%;">Name</div>
    <div class="pull-left GridCP" style="width: 20%;">Store Name</div>
    <div class="pull-left GridCP" style="width: 15%;">Phone</div>
    <div class="pull-left GridCP ACR" style="width: 30%;">Option(s)</div>
</div>
@{
    int count = 0;    
}
@foreach (var item in Model)
{
    count++;

    string activeIcon = (item.IsActive) ? "fa-ban" : "fa-check-circle-o";
    string activeTitle = (item.IsActive) ? "Disable Employee" : "Enable Employee";
            
    <div class="RC GridH @( ((count % 2) == 0) ? "GridAltBG" : "")">
        <div class="pull-left GridCP" style="width: 15%;">@Html.DisplayFor(modelItem => item.Code)</div>
        <div class="pull-left GridCP" style="width: 20%;">@Html.DisplayFor(modelItem => item.LastName) @Html.DisplayFor(modelItem => item.FirstName)</div>
        <div class="pull-left GridCP" style="width: 20%;">@Html.DisplayFor(modelItem => item.Store.Name)</div>
        <div class="pull-left GridCP" style="width: 15%;">@Html.DisplayFor(modelItem => item.Phone)</div>
        <div class="pull-left GridCP ACR" style="width: 30%;">
            @if (!item.SystemUserId.HasValue && item.IsManager)
            {
                @Html.ActionLink("Associate System User", "AssociateSystemUser", "User", new { id = item.Id }, new { @class = "btn btn-sm btn-primary", title = "Assocaite System User", style = "color:#fff !important;margin-top: -6px; margin-right:30px;" })
            }
            @Html.ActionLink(" ", "Details", "Employee", new { id = item.Id }, new { @class = "fa fa-eye", title = "View Employee" })@Html.ActionLink(" ", "Update", "Employee", new { id = item.Id }, new { @class = "fa fa-edit", title = "Edit Employee" })@Html.ActionLink(" ", "Activate", "Employee", new { id = item.Id, active = !item.IsActive }, new { @class = "fa " + activeIcon, title = activeTitle })
        </div>
    </div>
}
<div class="RC GridFooterBG GridAltBG GridCP GridFooterBG">Total Records: @Model.Count()</div>

source/OS.EMS.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

source/OS.EMS.Website/Views/Shared/_LayoutEMS.cshtml
@using OS.EMS.Model
@{
    var user = HttpContext.Current.Session["AppUser"] as SystemUser;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/Assets/KendoUI/Web/styles/kendo.common.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Assets/KendoUI/Web/styles/kendo.silver.min.css")" rel="stylesheet">

    @Styles.Render("~/Content/kendoui")
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->


</head>
<body class="bg-app">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button data-target=".bs-navbar-collapse" data-toggle="collapse" type="button" class="navbar-toggle collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brandX" href="@Url.Action("Dashboard", "Home")" style="padding-right:20px; line-height:49px;">
                    <img src="@Url.Content("~/Content/Images/Common/JITBLogo1.png")" /></a>
            </div>
            <nav role="navigation" class="navbar-collapse bs-navbar-collapse collapse" style="height: 1px;">

                <ul id="navMainMenu" class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Dashboard", "Home")">Dashboard</a>
                    </li>
                    <li>
                        @*<a href="#"></a>*@
                    </li>
                </ul>
                <div class="nav navbar-nav navbar-right">
                    <div id="dvLoginStatus" style="color: #fff; margin-left: 6px; margin-top: 16px;">
                        <div class="pull-right"><a href="@Url.Action("SignOut", "Login")" class="DashboardLogOut"><span class="glyphicon glyphicon-log-out"></span></a></div>
                        <div class="pull-right">
                            Welcome to 

                                @if (user != null)
                                {
                                    <strong>
                                        @(user.LastName + " " + user.FirstName)
                                    </strong>        
                                }

                        </div>
                    </div>
                </div>
            </nav>
        </div>

    </div>
    @RenderSection("SubHeader", required: false)

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" style="padding-bottom: 0px; margin-bottom: 10px;">
        <div class="container">
            @*<h2>Employment Management System</h2>
            <p>Jack in the Box is among the nation's leading fast-food hamburger chains, with more than 2200 quick-serve restaurants in 19 states.</p>*@
            @*<p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>*@
        </div>
    </div>

    <div class="container">
        @{Html.RenderPartial("_BreadCrumb");}
        @{Html.RenderPartial("PageMessage");}


        @RenderBody()
        <hr style="border: solid 1px #AE1128;">
        <footer>
            <div class="pull-left">&copy; JITB EMP Company 2014</div>
            <div class="pull-right">Build 0.2.0</div>
        </footer>
    </div>
    <br />
    <!-- /container -->

    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/kendoui")
    <script src="@Url.Content("~/Assets/KendoUI/Web/js/kendo.all.min.js")"></script>


    @RenderSection("scripts", required: false)
    <script src="@Url.Content("~/Scripts/HmeScript.js")"></script>

    <script>
        var appUser = '@(HttpContext.Current.Session["AppUser"])';
        if (appUser == "") {
            window.location = "../../../LogIn/SignOut";
            @*window.location = "@(HttpContext.Current.Request.UrlReferrer.AbsoluteUri)";*@
        }
    </script>
</body>
</html>

source/OS.EMS.Website/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    
        @Scripts.Render("~/bundles/jquery")

    <style>
        .form-signin
        {
            margin: 0 auto;
            max-width: 430px;
            padding: 15px;
        }
    </style>

    @Scripts.Render("~/bundles/modernizr")

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->


</head>
<body class="bg-app">

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">


        <div class="container">
            <div class="navbar-header">
                <button data-target=".bs-navbar-collapse" data-toggle="collapse" type="button" class="navbar-toggle collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brandX" href="../" style="padding-right: 20px; line-height: 49px;">
                    <img src="@Url.Content("~/Content/Images/Common/JITBLogo1.png")" /></a>
            </div>
            <nav role="navigation" class="navbar-collapse bs-navbar-collapse collapse" style="height: 1px;">
                <div class="nav navbar-nav"></div>
                <ul id="navMainMenu" class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="#">SignIn</a>
                    </li>
                    <li>
                        <a href="#">ContactUs</a>
                    </li>
                </ul>

            </nav>
        </div>

    </div>
    @* <br /><br />*@
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" style="padding-bottom: 0px; margin-bottom: 10px;">
        <div class="container">
            <h2>Employment Management System</h2>
            @*<p>Jack in the Box is among the nation's leading fast-food hamburger chains, with more than 2200 quick-serve restaurants in 19 states.</p>
            <p><a class="AncGrey" role="button">Learn more &raquo;</a></p>*@
        </div>
    </div>

    <div class="container">
        @{Html.RenderPartial("PageMessage");}
        @Html.Partial("_SignIn")

        @RenderBody()
        <hr style="border: solid 1px #AE1128;">
        <footer>
            <div class="pull-left">&copy; JITB EMP Company 2014</div>
            <div class="pull-right">Build 0.2.0</div>
        </footer>
    </div>
    <!-- /container -->
    @RenderSection("scripts", required: false)
    

</body>
</html>

source/OS.EMS.Website/Views/Shared/_QuickShortcuts.cshtml
@using OS.EMS.Web.Models
@{

    var user = HttpContext.Current.Session["AppUser"] as OS.EMS.Model.SystemUser;
    
}



<div class="row QuickShortCutsCont">

    <a href="@Url.Action("Create", "Applicant")" >
        <i class="fa fa-user"></i>
        <span>New Applicant</span>
    </a>


    @if (user != null && user.Role.Name  == RoleType.Admin.ToString())
    {
        <a href="@Url.Action("Create", "Store")">
            <i class="fa fa-building-o"></i>
            <span>New Store</span>
        </a>
        
        @*<a href="@Url.Action("Create", "User")">
            <i class="fa fa-user"></i>
            <span>New User</span>

        </a>*@
       
        
        
    }


    <a href="@Url.Action("List", "Applicant")">
        <i class="fa fa-users"></i>
        <span>Applicants</span>
    </a>


    <a href="@Url.Action("List", "Store")">
        <i class="fa fa-building-o"></i>
        <span>Stores</span>
    </a>

    @if (user != null && user.Role.Name == RoleType.Admin.ToString())
    {
        <a href="@Url.Action("ManagersList", "Employee")">
            <i class="fa fa-users"></i>
            <span>Managers</span>
        </a>

        <a href="@Url.Action("List", "User")">
            <i class="fa fa-users"></i>
            <span>User</span>
        </a>
    }



    <a href="#">
        <i class="fa fa-list-alt"></i>
        <span>Reports</span>
    </a>
</div>

source/OS.EMS.Website/Views/Shared/_SignIn.cshtml
@using (Html.BeginForm("SignIn", "Login", FormMethod.Post, new { id = "", @class = "form-signin" }))
{
        
    <div class="wellx well-smx" style="padding: 0 30px 30px 30px">
        <h2 class="form-signin-heading">Please Sign In</h2>

        <div class="row form-group">
            <div class="col-md-12">
                <div>User ID (Email Address)</div>
                <input id="EmailAddress" name="EmailAddress" type="text" autofocus="" required="" placeholder="Email address" class="form-control" maxlength="64" >
            </div>
        </div>

        <div class="row form-group">
            <div class="col-md-12">
                <div>Password</div>
                <input id="Password" name="Password" type="password" required="" placeholder="Password" class="form-control" maxlength="32">
            </div>
        </div>



        <label class="checkbox">
            <input type="checkbox" value="remember-me">
            Remember me
       
        </label>
        <button type="submit" class="btn  btn-primary btn-block">Sign in</button>
        @*@if (TempData["PageMessage"] != null)
        { 
            <div style="color: red;">@TempData["PageMessage"]</div>
        }*@
    </div>
}