source/OS.EMS.Website/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LinqToExcel;
using LinqToExcel.Domain;
using Ninject;
using OS.EMS.Model;
using OS.EMS.Services;
using OS.EMS.Model.Helper;
using OS.EMS.Web.Models;

namespace OS.EMS.Web.Controllers
{
    public class AttendanceController : BaseController
    {

        [Inject]
        public AttendanceController(IAttendanceService storeService, IAttendanceDataService attendanceDataService, IEmployeeService employeeService, IGeographyService geographyService)
        {
            AttendanceService = storeService;
            AttendanceDataService = attendanceDataService;
            EmployeeService = employeeService;
            GeographyService = geographyService;

        }

        public ActionResult Create()
        {
            var viewModel = new AttendanceVM();
            return View("CreateOrUpdate", viewModel);
        }

        [HttpPost]
        public ActionResult Create(AttendanceVM viewModel)
        {
            if (viewModel == null) return RedirectToAction("InvalidRequest", "Error");

            var store = viewModel.ToModel();
            if (AttendanceService.Create(store))
            {
                ShowMessage(Messages.CreateAttendanceSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("InvalidRequest", "Error");

        }

        public ActionResult Update(Guid? id)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            var store = AttendanceService.Get(id.Value);
            var viewModel = store.ToModelVM();
            return View("CreateOrUpdate", viewModel);
        }

        public ActionResult ListAttendanceData()
        {
            var attendanceData = AttendanceDataService.GetAll().OrderByDescending(a => a.Time).ThenBy(a=>a.Name);
            return View(attendanceData);
        }

        public ActionResult List()
        {
            var attendance = AttendanceService.GetAll();
            return View(attendance);
        }

        public ActionResult ImportExcel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ImportExcel(FormCollection frmColl)
        {

            if (Request.Files["FileUpload1"].ContentLength > 0)
            {
                string extension = System.IO.Path.GetExtension(Request.Files["FileUpload1"].FileName);
                string fileName = System.IO.Path.GetFileName(Request.Files["FileUpload1"].FileName);

                string filePath = string.Format("{0}/{1}", Server.MapPath(AppConstants.AttendanceFilesPath), fileName);
                if (System.IO.File.Exists(filePath))
                    System.IO.File.Delete(filePath);

                Request.Files["FileUpload1"].SaveAs(filePath);

                var excel = new ExcelQueryFactory(filePath);
                //excel.DatabaseEngine = DatabaseEngine.Ace;
                //var columnNames = excel.GetColumnNames("Sheet1"); 
                excel.AddMapping("AcountNo", "AC-No#");

                string worksheetName = "Sheet1";
                int worksheetIndex = 0;

                var attendanceData = excel.Worksheet<AttendanceData>(worksheetIndex).OrderBy(a => a.AcountNo).ToList();
                
                var cnt = attendanceData.Count();

                bool statusCreate = false;
                foreach (var data in attendanceData)
                {
                    statusCreate = AttendanceDataService.Create(data);
                }

                
                if (statusCreate)
                {
                    ShowMessage(Messages.CreateAttendanceSuccess, MessageType.Success);
                    return RedirectToAction("ListAttendanceData");
                }
                
            }

            return RedirectToAction("InvalidRequest", "Error");
        }

        
    }
}

source/OS.EMS.Website/Views/Attendance/CreateOrUpdate.cshtml
@model OS.EMS.Web.Models.AttendanceVM

@{
    ViewBag.Title = "CreateOrUpdate";
    Layout = "~/Views/Shared/_LayoutEMS.cshtml";
}

<h2>CreateOrUpdate</h2>

source/OS.EMS.Website/Views/Attendance/ImportExcel.cshtml
@{
    ViewBag.Title = "ImportExcel";
    Layout = "~/Views/Shared/_LayoutEMS.cshtml";
}

<h2>Import Attendance</h2>


@using (Html.BeginForm("ImportExcel", "Attendance", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-12 form-group">
            <input type="file" id="FileUpload1" name="FileUpload1" class="btn pull-left" style="margin-right: 10px;" /><input type="submit" id="Submit" class="btn btn-primary pull-left" name="Submit" value="Submit" />
        </div>
        @*<div class="col-md-2 form-group">
            
        </div>*@
    </div>
}

source/OS.EMS.Website/Views/Attendance/List.cshtml
@model IEnumerable<OS.EMS.Model.Attendance>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_LayoutEMS.cshtml";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SignIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SignOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeletedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedById)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedById)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeletedById)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SignIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SignOut)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeletedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedById)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedById)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeletedById)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

source/OS.EMS.Website/Views/Attendance/ListAttendanceData.cshtml
@model IEnumerable<OS.EMS.Model.AttendanceData>

@{
    ViewBag.Title = "ListAttendanceData";
    Layout = "~/Views/Shared/_LayoutEMS.cshtml";
}

<h2>Attendance Data</h2>

<p>
    @Html.ActionLink("Create New", "ImportExcel")
</p>
@if (Model != null)
{
    <div>Total Records: @Model.Count()</div>
}

<table style="width:98%">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AcountNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exception)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AcountNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Exception)
        </td>
        <td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id })
        </td>
    </tr>
}

</table>