source/OS.EMS.Website/Controllers/I9FormController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ninject;
using OS.EMS.Model;
using OS.EMS.Services;
using OS.EMS.Model.Helper;
using OS.EMS.Web.Models;

namespace OS.EMS.Web.Controllers
{
    public class I9FormController : BaseController
    {

        [Inject]
        public I9FormController(II9FormService i9FormService, IEmployeeService employeeService, IApplicantService applicantService, IStoreService storeService, IAttendanceService attendanceService, IGeographyService geographyService, IAcceptableDocumentServices acceptableDocumentService)
        {
            ApplicantService = applicantService;
            EmployeeService = employeeService;
            AttendanceService = attendanceService;
            StoreService = storeService;
            GeographyService = geographyService;
            I9FormService = i9FormService;
            AcceptableDocumentService = acceptableDocumentService;
        }


        #region CRUD Operations
        public ActionResult Create(Guid? id)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            var model = I9FormService.GetByEmployeeId(id.Value);
            var viewModel = model.ToViewModel();

            //Init Acceptable Documents
            InitAcceptableDoc(viewModel);

            return View("CreateOrUpdate", viewModel);
        }

        [HttpPost]
        public ActionResult Create(I9FormUSVM viewModel, FormCollection frmColl)
        {
            if (viewModel == null) return RedirectToAction("InvalidRequest", "Error");

            var I9FormUS = viewModel.ToModel();

            if (I9FormService.Create(I9FormUS))
            {

                //FOr Attach Documents
                foreach (string file in Request.Files)
                {
                    HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                    if (hpf.ContentLength == 0)
                        continue;


                    string dirPath = Server.MapPath(AppConstants.EmpDocPath + I9FormUS.Id);

                    if (!Directory.Exists(dirPath))
                    {
                        Directory.CreateDirectory(dirPath);
                    }

                    var newFileName = file + Path.GetExtension(hpf.FileName);
                    string savedFileName = Path.Combine(dirPath, newFileName);
                    hpf.SaveAs(savedFileName);
                }



                ShowMessage(Messages.CreateFormW7Success, MessageType.Success);
                //return SearchByExt("I9Form", new {id = form.EmployeeId});
                return RedirectToAction("Details", "Employee", new { id = I9FormUS.EmployeeId });
            }

            return RedirectToAction("InvalidRequest", "Error");
        }

        public ActionResult Update(Guid? id)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            var model = I9FormService.Get(id.Value);
            var viewModel = model.ToViewModel();

            if (viewModel.DocumentsA != null)
            {
                foreach (var item in viewModel.DocumentsA)
                {
                    item.DocumentType = GetAcceptableDocumentSLI();
                }
            }

            return View("CreateOrUpdate", viewModel);
        }

        [HttpPost]
        public ActionResult Update(I9FormUSVM viewModel)
        {
            if (viewModel == null || viewModel.Id == null) return RedirectToAction("InvalidRequest", "Error");

            var model = viewModel.ToModel();
            if (I9FormService.Update(model))
            {
                //For Accep Doc update
                foreach (var acceptableDocument in viewModel.DocumentsA.ToModel())
                {
                    AcceptableDocumentService.Update(acceptableDocument);
                }

                //For Attach Documents
                foreach (string file in Request.Files)
                {
                    HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                    if (hpf.ContentLength == 0)
                        continue;


                    string dirPath = Server.MapPath(AppConstants.EmpDocPath + model.Id);

                    if (!Directory.Exists(dirPath))
                    {
                        Directory.CreateDirectory(dirPath);
                    }

                    var newFileName = file + Path.GetExtension(hpf.FileName);
                    string savedFileName = Path.Combine(dirPath, newFileName);

                    //For Existing File
                    DirectoryInfo di = new DirectoryInfo(dirPath);
                    if (di.Exists)
                    {
                        FileInfo[] files = di.GetFiles(file + "*");
                        if (files != null && files.Any())
                        {
                            foreach (var fileInfo in files)
                            {
                                if (fileInfo.Exists)
                                {
                                    fileInfo.Delete();
                                }
                            }
                        }
                    }

                    hpf.SaveAs(savedFileName);
                }

                ShowMessage(Messages.UpdateI9Success, MessageType.Success);
                return RedirectToAction("Details", "Employee", new { id = model.EmployeeId });
            }

            return RedirectToAction("InvalidRequest", "Error");
        }

        #endregion

        #region AppHelper

        private void InitAcceptableDoc(I9FormUSVM viewModel)
        {
            var itm = GetAcceptableDocumentSLI();

            for (int i = 0; i < 6; i++)
            {
                var acceptableDocument = new AcceptableDocumentVM { DocumentType = itm, DocumentCode = "DC" + Guid.NewGuid() };
                viewModel.DocumentsA.Add(acceptableDocument);
            }

        }

        public List<SelectListItem> GetAcceptableDocumentSLI()
        {
            var acceptableDocumentSLI = new List<SelectListItem>
            {
                new SelectListItem {Value = "List A", Text = "List A"},
                new SelectListItem {Value = "List B", Text = "List B"},
                new SelectListItem {Value = "List C", Text = "List C"}
            };

            return acceptableDocumentSLI;
        }

        #endregion

    }


}

source/OS.EMS.Website/Views/I9Form/CreateOrUpdate.cshtml
@model I9FormUSVM
@using OS.EMS.Web.Models
@{
    ViewBag.Title = "I9FormUS";
    Layout = "~/Views/Shared/_LayoutEMS.cshtml";

    bool IsNewEntry = true;
    if (Model.Id.HasValue)
    {
        IsNewEntry = Model.Id.Value == Guid.Empty ? true : false;
    }
    
}
<h2 class="FontAE1128" style="margin-left: -10px;">@((IsNewEntry) ? "Create" : "Edit") I9 Form</h2>
<br />

<div class="">
    <ul class="nav nav-tabs">
        <li class="active"><a id="dvPersonalInfoSwitch" class="" role="button" style="">Personal Info</a></li>
        <li><a id="dvCitizenshipSwitch" class="" role="button" style="">Citizenship</a></li>
        <li><a id="dvDocumentsSwitch" class="" role="button" style="">Documents</a></li>
        <li><a id="dvPreparerSwitch" class="" role="button" style="">Preparer/Translator</a></li>
        <li><a id="dvCertificationSwitch" class="" role="button" style="">Employer Certification</a></li>
        <li><a id="dvRehireSwitch" class="" role="button" style="">Reverification and Rehires</a></li>
        @*<li><a id="dvExpireDocumentSwitch" class="" role="button" style="">Expire Document</a></li>
        <li><a id="dvSignatureSwitch" class="" role="button" style="">Signature</a></li>*@
    </ul>
    <br />
    
    @using (Html.BeginForm(Model.Id.Value == Guid.Empty ? "Create" : "Update", "I9Form", FormMethod.Post, new { id = "formi9", enctype = "multipart/form-data" }))
    {
        <div class="col-md-12 panel-body" style="background-color: #fff;">
            @Html.ValidationSummary(true)

            @Html.Partial("~/Views/I9Form/_PersonalInfo.cshtml", Model)
            @Html.Partial("~/Views/I9Form/_Citizenship.cshtml", Model)
            @Html.Partial("~/Views/I9Form/_Preparer.cshtml", Model)
            @Html.Partial("~/Views/I9Form/_Documents.cshtml", Model)
            @Html.Partial("~/Views/I9Form/_Certification.cshtml", Model)
            @Html.Partial("~/Views/I9Form/_Rehire.cshtml", Model)
            @*@Html.Partial("~/Views/I9Form/_ExpireDocument.cshtml", Model)
            @Html.Partial("~/Views/I9Form/_Signature.cshtml", Model)*@
            <hr/>
            <div class="row  form-group">
                <div class="col-md-12">
                    <input type="submit" value="@((IsNewEntry) ? "Create" : "Update")" class="btn btn-primary" style="min-width:75px;" />
                    @Html.ActionLink("Cancel", "Details", "Employee", new { id = Model.EmployeeId }, new { @class = "btn btn-primary btn-sm", style="min-width:75px;" })
                    @*@Html.HiddenFor(model => model.Id.Value)*@
                    <input type="hidden" id="id" name="id" value="@Model.Id"  />
                    @Html.HiddenFor(model => model.EmployeeId)
                    @Html.HiddenFor(model => model.IsActive)
                    @Html.ValidationSummary(true)
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        $(function () {
            
            //At PeronalInfo
            $("#DateOfBirth").kendoDatePicker();
            $("#AlienAuthorizedExpiryDate").kendoDatePicker();
            $("#SignatureDate").kendoDatePicker();
            $("#FirstDayDate").kendoDatePicker();
            $("#RehireDate").kendoDatePicker();
            $("#DocumentExpiryDate").kendoDatePicker();
            $("#EmployerSignatureDate").kendoDatePicker();
            $("#RepresentativeSignatureDate").kendoDatePicker();
            $("#RepresentativeSignatureDate").kendoDatePicker();
            $("#EmployerSignatureDate").kendoDatePicker();
            

            $("#SocialSecurityNumber").mask("999-99-9999");
            $("#Phone").mask("(999)999-9999");
            

            //$(function () {
                // ;
                $(".bind-ExpiryDate").each(function () {
                    // ;
                    $("#" + this.id).kendoDatePicker();
                });
            //});
           
            $("#PreparerSignatureDate").kendoDatePicker();
            

            //For Tabs
            //For Tabs
            $(".nav-tabs a").click(function () {
                // ;

                var isValidForm = $("#formi9").valid();
                if (isValidForm) {
                    EMSPanelHide();

                    $(".nav-tabs li").removeClass("active");
                    $(this).parent().addClass("active");

                    //For Panels
                    if ($(this).attr("id") == "dvPersonalInfoSwitch") {
                        $("#dvPersonalInfoContents").addClass("EmpPanelActive");

                    }
                    else if ($(this).attr("id") == "dvCitizenshipSwitch") {
                        $("#dvCitizenshipConents").addClass("EmpPanelActive");
                    }
                    else if ($(this).attr("id") == "dvPreparerSwitch") {
                        $("#dvPreparerConents").addClass("EmpPanelActive");
                    }
                    else if ($(this).attr("id") == "dvDocumentsSwitch") {
                        $("#dvDocumentsConents").addClass("EmpPanelActive");
                    }
                    else if ($(this).attr("id") == "dvCertificationSwitch") {
                        $("#dvCertificationConents").addClass("EmpPanelActive");
                    }
                    else if ($(this).attr("id") == "dvRehireSwitch") {
                        $("#dvRehireConents").addClass("EmpPanelActive");
                    }
                    //else if ($(this).attr("id") == "dvExpireDocumentSwitch") {
                    //    $("#dvExpireDocumentConents").addClass("EmpPanelActive");
                    //}
                    //else if ($(this).attr("id") == "dvSignatureSwitch") {
                    //    $("#dvSignatureConents").addClass("EmpPanelActive");
                    //}
                }

            });
            
       

        });

        function EMSPanelHide() {
            // 
            $(".EmpPanelActive").each(function () {
                $(this).removeClass("EmpPanelActive").addClass("EmpPanelHide");
            });
        }
        

    </script>

}

source/OS.EMS.Website/Views/I9Form/_Certification.cshtml
@model OS.EMS.Web.Models.I9FormUSVM
<div id="dvCertificationConents" class="EmpPanelHide">
    <div class="row">
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.RepresentativeTitle)
            @Html.TextBoxFor(model => model.RepresentativeTitle, new { @class = "form-control input-sm" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.RepresentativeLastName)
            @Html.TextBoxFor(model => model.RepresentativeLastName, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.RepresentativeFirstName)
            @Html.TextBoxFor(model => model.RepresentativeFirstName, new { @class = "form-control input-sm" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.RepresentativeOrganisation)
            @Html.TextBoxFor(model => model.RepresentativeOrganisation, new { @class = "form-control input-sm" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 form-group">
            <div>
                @Html.LabelFor(model => model.RepresentativeStreetAddress)
            </div>
            @Html.TextAreaFor(model => model.RepresentativeStreetAddress, new { style = "height:60px;", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RepresentativeStreetAddress)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.RepresentativeCity)
            @Html.TextBoxFor(model => model.RepresentativeCity, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.RepresentativeState)
            @Html.TextBoxFor(model => model.RepresentativeState, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.RepresentativeZipCode)
            @Html.TextBoxFor(model => model.RepresentativeZipCode, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.RepresentativeSignatureDate)
            @Html.TextBoxFor(model => model.RepresentativeSignatureDate, new { @class = "form-controlx input-smx KenDateFix" })
        </div>
    </div>


</div>

source/OS.EMS.Website/Views/I9Form/_Citizenship.cshtml
@model OS.EMS.Web.Models.I9FormUSVM



<div id="dvCitizenshipConents" class="EmpPanelHide">
    <div class="row">
        <div class="col-md-5  form-group">
            @Html.CheckBoxFor(model => model.IsCitizen)
            @Html.LabelFor(model => model.IsCitizen)
        </div>
    </div>
    <div class="row">
        <div class="col-md-5  form-group">
            @Html.CheckBoxFor(model => model.IsNonCitizenNational)
            @Html.LabelFor(model => model.IsNonCitizenNational)
        </div>
    </div>
    <div class="row">
        <div class="col-md-5  form-group">
            @Html.CheckBoxFor(model => model.IsLawfulResident)
            @Html.LabelFor(model => model.IsLawfulResident)
        </div>
    </div>
    <div class="row">
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.AlienRegistrationNumber)
            @Html.TextBoxFor(model => model.AlienRegistrationNumber, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.I9FormAdmissionNumber)
            @Html.TextBoxFor(model => model.I9FormAdmissionNumber, new { @class = "form-control input-sm" })
        </div>

    </div>
    <div class="row">
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.ForeignPassportNumber)
            @Html.TextBoxFor(model => model.ForeignPassportNumber, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.CountryOfIssuance)
            @Html.TextBoxFor(model => model.CountryOfIssuance, new { @class = "form-control input-sm" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.SignatureDate)
            @Html.TextBoxFor(model => model.SignatureDate, new { @class = "form-controlx input-smx KenDateFix" })
        </div>
    </div>
</div>

source/OS.EMS.Website/Views/I9Form/_Documents.cshtml
@model OS.EMS.Web.Models.I9FormUSVM



<div id="dvDocumentsConents" class="EmpPanelHide">
    <div class="xrow">
         @Html.EditorFor(model => model.DocumentsA)
    </div>
</div>

source/OS.EMS.Website/Views/I9Form/_ExpireDocument.cshtml
@model OS.EMS.Web.Models.I9FormUSVM
<div id="dvExpireDocumentConents" class="EmpPanelHide">
    <div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.DocumentTitle)
            @Html.TextBoxFor(model => model.DocumentTitle, new { @class = "form-control input-sm" })
        </div>
    </div>
    <div>
        <div>
            <div class="col-md-2  form-group">
                @Html.LabelFor(model => model.DocumentNumber)
                @Html.TextBoxFor(model => model.DocumentNumber, new { @class = "form-control input-sm" })
            </div>
        </div>
    </div>
    <div>
        <div>
            <div class="col-md-2  form-group">
                @Html.LabelFor(model => model.DocumentExpiryDate)
                @Html.TextBoxFor(model => model.DocumentExpiryDate, new { @class = "form-controlx input-smx" })
            </div>
        </div>
    </div>
    <div>
        <div>
            <div class="col-md-2  form-group">
                @Html.LabelFor(model => model.DocumentExpiryDate)
                @Html.TextBoxFor(model => model.DocumentExpiryDate, new { @class = "form-controlx input-smx" })
            </div>
        </div>
    </div>
</div>

source/OS.EMS.Website/Views/I9Form/_PersonalInfo.cshtml
@model OS.EMS.Web.Models.I9FormUSVM

<div id="dvPersonalInfoContents" class="EmpPanelActive">
    <div class="row">

        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.LastName)
            @Html.TextBoxFor(model => model.LastName, new { @class = "form-control input-sm", style = " " })
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
        <div class="col-md-3 form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.MiddleInitial)
            @Html.TextBoxFor(model => model.MiddleInitial, new { @class = "form-control input-sm", style = "" })
            @Html.ValidationMessageFor(model => model.MiddleInitial)
        </div>
        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.OtherNames) (if Any)
            @Html.TextBoxFor(model => model.OtherNames, new { @class = "form-control input-sm", style = " " })
            @Html.ValidationMessageFor(model => model.OtherNames)
        </div>
    </div>
    <div class="row">
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.DateOfBirth)<br />
            @Html.TextBoxFor(model => model.DateOfBirth, new { @class="KenDateFix" }) (e.g: mm/dd/yyyy)<br />
            @Html.ValidationMessageFor(model => model.DateOfBirth)
        </div>
        <div class="col-md-8  form-group">
            @Html.LabelFor(model => model.SocialSecurityNumber)<br />
            @Html.TextBoxFor(model => model.SocialSecurityNumber, new { @class = "form-control input-sm", style = "width:150px; display:inline-block; " }) (e.g: 999-99-9999)<br />
            @Html.ValidationMessageFor(model => model.SocialSecurityNumber)
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 form-group">
            <div>
                @Html.LabelFor(model => model.StreetAddress) (Street Name & Number)
            </div>
            @Html.TextBoxFor(model => model.StreetAddress, new { style = "", @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.StreetAddress)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.ApartmentNumber)
            @Html.TextBoxFor(model => model.ApartmentNumber, new { @class = "form-control input-sm", style = "" })
            @Html.ValidationMessageFor(model => model.ApartmentNumber)
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.City)
            @Html.TextBoxFor(model => model.City, new { @class = "form-control input-sm", style = "" })
            @Html.ValidationMessageFor(model => model.City)
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.State)
            @Html.TextBoxFor(model => model.State, new { @class = "form-control input-sm", style = "" })
            @Html.ValidationMessageFor(model => model.State)
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.ZipCode)
            @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control input-sm", style = "" })
            @Html.ValidationMessageFor(model => model.ZipCode)
        </div>
    </div>
    <div class="row">

        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.Email)
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-sm", style = "" })
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.Phone)<br />
            @Html.TextBoxFor(model => model.Phone, new { @class = "form-control input-sm", style = "width:150px; display:inline-block;" }) (e.g: ((999)999-9999))<br />
            @Html.ValidationMessageFor(model => model.Phone)
        </div>
    </div>
</div>

source/OS.EMS.Website/Views/I9Form/_Preparer.cshtml
@model OS.EMS.Web.Models.I9FormUSVM
<div id="dvPreparerConents" class="EmpPanelHide">

    <div class="row">
        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.PreparerSignatureDate)
            @Html.TextBoxFor(model => model.PreparerSignatureDate, new { @class = "form-controlx input-smx KenDateFix" })
            @Html.ValidationMessageFor(model => model.PreparerSignatureDate)
        </div>
    </div>
    <div class="row">
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.PreparerLastName)
            @Html.TextBoxFor(model => model.PreparerLastName, new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.PreparerLastName)
        </div>
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.PreparerFirstName)
            @Html.TextBoxFor(model => model.PreparerFirstName, new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.PreparerFirstName)
        </div>
    </div>
    <div class="row">
        <div class="col-md-6  form-group">
            @Html.LabelFor(model => model.PreparerStreetAddress)
            @Html.TextAreaFor(model => model.PreparerStreetAddress, new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.PreparerStreetAddress)
        </div>
    </div>
    <div class="row">

        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.PreparerCity)
            @Html.TextBoxFor(model => model.PreparerCity, new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.PreparerCity)
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.PreparerState)
            @Html.TextBoxFor(model => model.PreparerState, new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.PreparerState)
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.PreparerZipCode)
            @Html.TextBoxFor(model => model.PreparerZipCode, new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.PreparerZipCode)
        </div>
    </div>

</div>

source/OS.EMS.Website/Views/I9Form/_Rehire.cshtml
@model OS.EMS.Web.Models.I9FormUSVM
<div id="dvRehireConents" class="EmpPanelHide">
    <div class="row">
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.RehireDate)
            @Html.TextBoxFor(model => model.RehireDate, new { @class = "form-controlx input-smx KenDateFix" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.RehireLastName)
            @Html.TextBoxFor(model => model.RehireLastName, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.RehireFirstName)
            @Html.TextBoxFor(model => model.RehireFirstName, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.RehireMiddleInitial)
            @Html.TextBoxFor(model => model.RehireMiddleInitial, new { @class = "form-control input-sm" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-4  form-group">
            @Html.LabelFor(model => model.DocumentTitle)
            @Html.TextBoxFor(model => model.DocumentTitle, new { @class = "form-control input-sm" })
        </div>
    </div>
    <div class="row">




        <div class="col-md-3  form-group">
            @Html.LabelFor(model => model.DocumentNumber)
            @Html.TextBoxFor(model => model.DocumentNumber, new { @class = "form-control input-sm" })
        </div>
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.DocumentExpiryDate)
            @Html.TextBoxFor(model => model.DocumentExpiryDate, new { @class = "form-controlx input-smx KenDateFix" })
        </div>
    </div>


</div>

source/OS.EMS.Website/Views/I9Form/_Signature.cshtml
@model OS.EMS.Web.Models.I9FormUSVM
<div id="dvSignatureConents" class="EmpPanelHide">
    <div class="row">
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.EmployerSignatureDate)
            @Html.TextBoxFor(model => model.EmployerSignatureDate, new { @class = "form-controlx input-smx" })
        </div>                    
        <div class="col-md-2  form-group">
            @Html.LabelFor(model => model.EmployerPrintName)
            @Html.TextBoxFor(model => model.EmployerPrintName, new { @class = "form-control input-sm" })
        </div>                    
    </div>
</div>