source/OS.EMS.Website/Controllers/EmployeeDesignationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ninject;
using OS.EMS.Model;
using OS.EMS.Services;
using OS.EMS.Web.Models;

namespace OS.EMS.Web.Controllers
{
    public class EmployeeDesignationController : BaseController
    {
        [Inject]
        public EmployeeDesignationController(IEmployeeDesignationService positionDesiredService)
        {
            EmployeeDesignationService = positionDesiredService;
        }

        #region CRUD Operations

        public ActionResult Create()
        {
            var viewModel = new EmployeeDesignationVM();
            return View("CreateOrUpdate", viewModel);

        }

        [HttpPost]
        public ActionResult Create(EmployeeDesignationVM viewModel)
        {
            if (viewModel == null) return RedirectToAction("InvalidRequest", "Error");

            var employeeDesignation = viewModel.ToModel();

            if (EmployeeDesignationService.Create(employeeDesignation))
            {
                ShowMessage(Messages.CreateDesignationSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("InvalidRequest", "Error");

        }

        public ActionResult Update(Guid? id)
        {
            if (id == null) return RedirectToAction("NotFound", "Error");

            var employeeDesignation = EmployeeDesignationService.Get(id.Value);
            var viewModel = employeeDesignation.ToModelVM();
            return View("CreateOrUpdate", viewModel);
        }

        [HttpPost]
        public ActionResult Update(EmployeeDesignationVM viewModel)
        {
            if (viewModel == null || viewModel.Id == null) return RedirectToAction("InvalidRequest", "Error");

            var store = viewModel.ToModel();

            if (EmployeeDesignationService.Update(store))
            {
                ShowMessage(Messages.UpdateDesignationSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("InvalidRequest", "Error");

        }

        public ActionResult List()
        {
            var models = EmployeeDesignationService.GetAll();
            var viewModels = models.ToEmployeeDesignationVM();
            return View(viewModels);
        }

        public ActionResult Activate(Guid? id, bool active)
        {
            if (!id.HasValue) return RedirectToAction("InvalidRequest", "Error");

            if (EmployeeDesignationService.Activate(id.Value, active))
            {
                ShowMessage(active ? Messages.ActivateDesignationSuccess : Messages.DeactivateDesignationSuccess, MessageType.Success);
                return RedirectToAction("List");
            }

            return RedirectToAction("List");
        }
        #endregion
    }
}

source/OS.EMS.Website/Views/EmployeeDesignation/CreateOrUpdate.cshtml
@model OS.EMS.Web.Models.EmployeeDesignationVM

@{
    ViewBag.Title = "Create Employee Position";
    Layout = "~/Views/Shared/_LayoutEMS.cshtml";

    bool IsNewEntry = true;
    if (Model.Id.HasValue)
    {
        IsNewEntry = Model.Id.Value == Guid.Empty ? true : false;
    }
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-building-o"></i>@((IsNewEntry) ? "Create" : "Edit") Employee Position</h3>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm())
        {
           
            <div class="row">
                <div class="col-md-3 form-group">
                    <div>
                        Position
                    </div>
                    @Html.TextBoxFor(model => model.Designation, new { @class = "form-control input-sm", style = " " })
                    @Html.ValidationMessageFor(model => model.Designation)

                </div>
            </div>
              
            
      
            <div class="row  form-group">
                <div class="col-md-12">
                    <input type="submit" value="@((IsNewEntry) ? "Create" : "Update")" class="btn btn-primary"  style="min-width:75px;" />
                    @if (IsNewEntry)
                    { 
                        @Html.ActionLink("Cancel", "Dashboard", "Home", null, new { @class = "btn btn-primary btn-sm", style = "min-width:75px;" });
                    }
                    else
                    {
                        @Html.ActionLink("Cancel", "List", "EmployeeDesignation", new { id = Model.Id.Value }, new { @class = "btn btn-primary btn-sm", style = "min-width:75px;" });
                    }
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.IsActive)
                    @Html.ValidationSummary(true)
                </div>
            </div>

        }

    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            //At PeronalInfo
            $("#XDate").kendoDatePicker();
            $("#Phone").mask("(999)999-9999");
        });
    </script>
}

source/OS.EMS.Website/Views/EmployeeDesignation/List.cshtml
@model IEnumerable<OS.EMS.Web.Models.EmployeeDesignationVM>

@{
    ViewBag.Title = "UserList";
    Layout = "~/Views/Shared/_LayoutEMS.cshtml";
}

<div class="panel panel-default ">
    <div class="panel-heading">
        <h3 class="panel-title FB pull-left"><i class="fa fa-users"></i>Employee's Designations</h3>
        <div class="btn-group btn-group-style-ext pull-right">
            @Html.ActionLink("New Designation", "Create", null, new { @class = "btn btn-default btn-sm" })
        </div>
    </div>
    <div class="panel-body" style="padding: 0px;">
        <div class="RC GridHeaderBG">
            <div class="pull-left GridCP" style="width: 70%;">Position</div>
            <div class="pull-right GridCP ACR" style="width: 30%;">Option(s)</div>
        </div>
        @{
            int count = 0;    
        }
        @foreach (var item in Model)
        {
            count++;

            string tmp = (count % 2).ToString();

            string activeIcon = (item.IsActive) ? "fa-ban" : "fa-check-circle-o";
            string activeTitle = (item.IsActive) ? "Disable User" : "Enable User";
            
            
            <div class="RC GridH @( ((count % 2) == 0) ? "GridAltBG" : "")">
                <div class="pull-left GridCP" style="width: 70%;">@Html.DisplayFor(modelItem => item.Designation)</div>
                <div class="pull-right GridCP ACR" style="width: 30%;">@*@Html.ActionLink(" ", "Update", new { id = item.Id }, new { @class = "fa fa-edit", title = "Edit User" })&nbsp;*@@Html.ActionLink(" ", "Activate", new { id = item.Id, active = !item.IsActive }, new { @class = "fa " + activeIcon, title = activeTitle }) </div>
            </div>
        }
        <div class="RC GridFooterBG GridAltBG GridCP GridFooterBG">Total Records: @Model.Count()</div>

    </div>
</div>